<!doctype html>
<html lang="en">

<?php include("inc/head.php"); ?>

<body>
    <!--nav bar-->
    <?php include("inc/nav.php"); ?>
    <!--End of Nav Bar -->

    <main>
        <!-- this section contains the form for a user to add a new team-->
        <div class="container">
            <h1 id="addTeambanner"> Add a Team</h1>
            <p>Select the appropriate division for your team and complete the form below. Once all information
                has been entered, click submit to add your team. </p>

            <form id="addTeamForm">
                <div class="row">
                    <div class="col-md-4">
                        <label class="form-check-label" for="leagueList">League</label>
                        <select class="custom-select" id="leagueList" name="leaguecode">
                            <option value=-1 selected>Choose one</option>
                            <!-- the dropdown selection will be generated by javascript-->
                        </select>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="teamname">Team Name</label>
                        <input type="text" class="form-control" id="teamname" name="teamname" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="managername">Manager Name</label>
                        <input type="text" class="form-control" id="managername" name="managername" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="managerphone">Manager Phone</label>
                        <input type="tel" class="form-control" id="managerphone" name="managerphone" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="manageremail">Manager Email</label>
                        <input type="email" class="form-control" id="manageremail" name="manageremail" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="maxteammembers">Max # Team Members</label>
                        <input type="text" class="form-control" id="maxteammembers" name="maxteammembers" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="minmemberage">Minimum Member Age</label>
                        <input type="text" class="form-control" id="minmemberage" name="minmemberage" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="maxmemberage">Maximum Member Age</label>
                        <input type="text" class="form-control" id="maxmemberage" name="maxmemberage" required>
                    </div>
                </div>

                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="teamgender" id="male" value="Male">
                    <label class="form-check-label" for="male">Male</label>
                </div>

                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="teamgender" id="female" value="Female">
                    <label class="form-check-label" for="female">Female</label>
                </div>

                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="teamgender" id="any" value="Any">
                    <label class="form-check-label" for="any">Any</label>
                </div>

                <div class="container">
                    <div class="row">
                        <button type="button" id="submitBtn" class="btn btn-info mt-3">Submit</button>
                        <button type="reset" id="resetBtn" class="btn btn-info mt-3 ml-3">Reset</button>
                        <a href="#" id="cancelBtn" class="btn btn-info mt-3 ml-3" role="button">Cancel</a>
                    </div>
                </div>
            </form>

            <!-- this section will display any possible error messages-->

            <div class="container">
                <div id="msgDiv">
                    <ul id="errorMessages"></ul>
                </div>
            </div>
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <?php include("inc/includes.php"); ?>
    <script src="scripts/addTeam.js"></script>
</body>

</html>